### ISSUE TITLE
How can I change the logo on the first page?

### ISSUE THREAD

**Issue by reem-alseed** [sabirdvd/LaTeX-template-for-UPC-thesis-#1]

**Comment by sabirdvd** [comment]
Hi, please refer to ociamthesis.cls line 72  

https://github.com/sabirdvd/LaTeX-template-for-UPC-thesis-/blob/ef3c0aff89478de769b8d3875e048595bdfadfe3/ociamthesis.cls#L72

**Comment by reem-alseed** [comment]
so the logo is a pdf file ?

**Comment by sabirdvd** [comment]
Yes, I think having a pdf as a picture is better (in terms of quality) than a jpg image.
